version: 2

updates:
  # Update github actions
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "[github-actions] "
    directories:
      - "/"
      - "/src/Cathal.PcfTools.MSBuild.Proj/contentFiles/.github/workflows"
    schedule:
      interval: "weekly"
    target-branch: "main"

  # Update devcontainer
  - package-ecosystem: "devcontainers"
    commit-message:
      prefix: "[devcontainer] "
    directories:
      - "/"
      - "/src/Cathal.PcfTools.MSBuild.Proj/contentFiles/"
    schedule:
      interval: "weekly"
    target-branch: "main"
