name: Build

on:
  push:
    branches:
      - '**'

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Setup: Checkout the repo"
        uses: actions/checkout@v5
      - name: "Setup: Setup dotnet"
        uses: actions/setup-dotnet@v4
      - name: "Setup: Node"
        uses: actions/setup-node@v5
        with:
          node-version-file: src/Cathal.PcfTools.MSBuild.Proj/contentFiles/.nvmrc
      - name: "Build: Restore the test folder"
        run: |
          dotnet restore
        working-directory: test
        shell: bash
      - name: "Build: Build the test folder"
        run: |
          dotnet build --no-restore
        working-directory: test
        shell: bash
      - name: "Test: Run tests in the test folder"
        run: |
          dotnet test --no-build
        working-directory: test
        shell: bash
      - name: "Validate: Check managed solution exists"
        run: |-
          file_path="$(pwd)/test/dist/sample_solution_0_1_2_managed.zip"
          if [ -f "$file_path" ]; then
            echo "File found: $file_path"
          else
            echo "File not found: $file_path"
            exit 1
          fi
        shell: bash
      - name: "Test: dotnet test"
        run: |
          dotnet test
        working-directory: test
      - name: "Test: UpdatePcfPackagesVersion"
        run: |
          dotnet msbuild test -t:UpdatePcfPackagesVersion -p:NewVersion=1.26.5
      - name: "Test: UpdatePcfTemplateFiles"
        run: |
          dotnet msbuild test -t:UpdatePcfTemplateFiles
      - name: "Test: SetVersion"
        run: |
          dotnet msbuild test -t:SetVersion -p:NewVersion=1.2.3
      - name: "Test: IncludeGitHubRepositoryUrl"
        run: |
          dotnet msbuild test -t:IncludeGitHubRepositoryUrl -p:GitHubRepositoryUrl=${{ github.server_url }}/${{ github.repository }}
      - name: "Test: Print git status"
        run: |
          git --no-pager status
      - name: "Test: Print git diff"
        run: |
          git --no-pager diff
      - name: "Artifacts: Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}__extract_this_zip
          path: ./test/dist/*
          retention-days: 15
        if: matrix.os == 'ubuntu-latest'
