name: Release

on:
  release:
    types:
      - published

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: "Setup: Checkout the repo"
        uses: actions/checkout@v3
      - name: "Setup: Setup dotnet"
        uses: actions/setup-dotnet@v3
      - name: "Setup: Node"
        uses: actions/setup-node@v3
        with:
          # Use the .nvmrc file from the package contents
          node-version-file: src/Cathal.PcfTools.Proj/contentFiles/.nvmrc

      # Configure environment variables
      - name: "Configure: Version"
        run: echo "Version=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      # Pack and publish
      - name: "Pack: dotnet pack src"
        run: dotnet pack src
      - name: "Publish: dotnet publish src"
        run: dotnet publish src
        env:
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
