name: Test

on:
  push:
    branches:
      - '**'

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Setup
      - name: "Setup: Checkout the repo"
        uses: actions/checkout@v3
      - name: "Setup: Setup dotnet"
        uses: actions/setup-dotnet@v3
      - name: "Setup: Node"
        uses: actions/setup-node@v3
        with:
          # Use the .nvmrc file from the package contents
          node-version-file: src/Cathal.PcfTools.MSBuild.Proj/contentFiles/.nvmrc

      # Build
      - name: "Build: Build the test folder"
        run: dotnet build test
        shell: bash

      # Validate
      - name: "Validate: Check managed solution exists"
        run: |-
          file_path="$(pwd)/test/dist/sample_solution_1_2_3_4_managed.zip"
          if [ -f "$file_path" ]; then
            echo "File found: $file_path"
          else
            echo "File not found: $file_path"
            exit 1
          fi
        shell: bash
